## static_countries
UPDATE static_countries SET cn_short_ar='أندورا',cn_iso_2='AD' WHERE cn_iso_2='AD';
UPDATE static_countries SET cn_short_ar='الإمارات العربية المتحدة',cn_iso_2='AE' WHERE cn_iso_2='AE';
UPDATE static_countries SET cn_short_ar='أفغانستان',cn_iso_2='AF' WHERE cn_iso_2='AF';
UPDATE static_countries SET cn_short_ar='أنتيغوا وبربودا',cn_iso_2='AG' WHERE cn_iso_2='AG';
UPDATE static_countries SET cn_short_ar='أنغويلا',cn_iso_2='AI' WHERE cn_iso_2='AI';
UPDATE static_countries SET cn_short_ar='ألبانيا',cn_iso_2='AL' WHERE cn_iso_2='AL';
UPDATE static_countries SET cn_short_ar='أرمينيا',cn_iso_2='AM' WHERE cn_iso_2='AM';
UPDATE static_countries SET cn_short_ar='أنغولا',cn_iso_2='AO' WHERE cn_iso_2='AO';
UPDATE static_countries SET cn_short_ar='أنتاركتيكا',cn_iso_2='AQ' WHERE cn_iso_2='AQ';
UPDATE static_countries SET cn_short_ar='الأرجنتين',cn_iso_2='AR' WHERE cn_iso_2='AR';
UPDATE static_countries SET cn_short_ar='ساموا الأمريكية',cn_iso_2='AS' WHERE cn_iso_2='AS';
UPDATE static_countries SET cn_short_ar='النمسا',cn_iso_2='AT' WHERE cn_iso_2='AT';
UPDATE static_countries SET cn_short_ar='أستراليا',cn_iso_2='AU' WHERE cn_iso_2='AU';
UPDATE static_countries SET cn_short_ar='آروبا',cn_iso_2='AW' WHERE cn_iso_2='AW';
UPDATE static_countries SET cn_short_ar='أذربيجان',cn_iso_2='AZ' WHERE cn_iso_2='AZ';
UPDATE static_countries SET cn_short_ar='البوسنة والهرسك',cn_iso_2='BA' WHERE cn_iso_2='BA';
UPDATE static_countries SET cn_short_ar='بربادوس',cn_iso_2='BB' WHERE cn_iso_2='BB';
UPDATE static_countries SET cn_short_ar='بنجلاديش',cn_iso_2='BD' WHERE cn_iso_2='BD';
UPDATE static_countries SET cn_short_ar='بلجيكا',cn_iso_2='BE' WHERE cn_iso_2='BE';
UPDATE static_countries SET cn_short_ar='بوركينا فاسو',cn_iso_2='BF' WHERE cn_iso_2='BF';
UPDATE static_countries SET cn_short_ar='بلغاريا',cn_iso_2='BG' WHERE cn_iso_2='BG';
UPDATE static_countries SET cn_short_ar='البحرين',cn_iso_2='BH' WHERE cn_iso_2='BH';
UPDATE static_countries SET cn_short_ar='بوروندي',cn_iso_2='BI' WHERE cn_iso_2='BI';
UPDATE static_countries SET cn_short_ar='بنين',cn_iso_2='BJ' WHERE cn_iso_2='BJ';
UPDATE static_countries SET cn_short_ar='برمودا',cn_iso_2='BM' WHERE cn_iso_2='BM';
UPDATE static_countries SET cn_short_ar='بروناي',cn_iso_2='BN' WHERE cn_iso_2='BN';
UPDATE static_countries SET cn_short_ar='بوليفيا',cn_iso_2='BO' WHERE cn_iso_2='BO';
UPDATE static_countries SET cn_short_ar='البرازيل',cn_iso_2='BR' WHERE cn_iso_2='BR';
UPDATE static_countries SET cn_short_ar='الباهاما',cn_iso_2='BS' WHERE cn_iso_2='BS';
UPDATE static_countries SET cn_short_ar='بوتان',cn_iso_2='BT' WHERE cn_iso_2='BT';
UPDATE static_countries SET cn_short_ar='جزيرة بوفيه',cn_iso_2='BV' WHERE cn_iso_2='BV';
UPDATE static_countries SET cn_short_ar='بتسوانا',cn_iso_2='BW' WHERE cn_iso_2='BW';
UPDATE static_countries SET cn_short_ar='روسيا البيضاء',cn_iso_2='BY' WHERE cn_iso_2='BY';
UPDATE static_countries SET cn_short_ar='بليز',cn_iso_2='BZ' WHERE cn_iso_2='BZ';
UPDATE static_countries SET cn_short_ar='كندا',cn_iso_2='CA' WHERE cn_iso_2='CA';
UPDATE static_countries SET cn_short_ar='جزر كوكوس',cn_iso_2='CC' WHERE cn_iso_2='CC';
UPDATE static_countries SET cn_short_ar='جمهورية الكونغو الديمقراطية',cn_iso_2='CD' WHERE cn_iso_2='CD';
UPDATE static_countries SET cn_short_ar='جمهورية أفريقيا الوسطى',cn_iso_2='CF' WHERE cn_iso_2='CF';
UPDATE static_countries SET cn_short_ar='جمهورية الكونغو',cn_iso_2='CG' WHERE cn_iso_2='CG';
UPDATE static_countries SET cn_short_ar='سويسرا',cn_iso_2='CH' WHERE cn_iso_2='CH';
UPDATE static_countries SET cn_short_ar='ساحل العاج',cn_iso_2='CI' WHERE cn_iso_2='CI';
UPDATE static_countries SET cn_short_ar='جزر كوك',cn_iso_2='CK' WHERE cn_iso_2='CK';
UPDATE static_countries SET cn_short_ar='شيلي',cn_iso_2='CL' WHERE cn_iso_2='CL';
UPDATE static_countries SET cn_short_ar='الكاميرون',cn_iso_2='CM' WHERE cn_iso_2='CM';
UPDATE static_countries SET cn_short_ar='الصين',cn_iso_2='CN' WHERE cn_iso_2='CN';
UPDATE static_countries SET cn_short_ar='كولومبيا',cn_iso_2='CO' WHERE cn_iso_2='CO';
UPDATE static_countries SET cn_short_ar='كوستاريكا',cn_iso_2='CR' WHERE cn_iso_2='CR';
UPDATE static_countries SET cn_short_ar='كوبا',cn_iso_2='CU' WHERE cn_iso_2='CU';
UPDATE static_countries SET cn_short_ar='الرأس الأخضر',cn_iso_2='CV' WHERE cn_iso_2='CV';
UPDATE static_countries SET cn_short_ar='جزيرة الكريسماس',cn_iso_2='CX' WHERE cn_iso_2='CX';
UPDATE static_countries SET cn_short_ar='قبرص',cn_iso_2='CY' WHERE cn_iso_2='CY';
UPDATE static_countries SET cn_short_ar='جمهورية التشيك',cn_iso_2='CZ' WHERE cn_iso_2='CZ';
UPDATE static_countries SET cn_short_ar='ألمانيا',cn_iso_2='DE' WHERE cn_iso_2='DE';
UPDATE static_countries SET cn_short_ar='جيبوتي',cn_iso_2='DJ' WHERE cn_iso_2='DJ';
UPDATE static_countries SET cn_short_ar='الدانمرك',cn_iso_2='DK' WHERE cn_iso_2='DK';
UPDATE static_countries SET cn_short_ar='دومينيكا',cn_iso_2='DM' WHERE cn_iso_2='DM';
UPDATE static_countries SET cn_short_ar='جمهورية الدومينيك',cn_iso_2='DO' WHERE cn_iso_2='DO';
UPDATE static_countries SET cn_short_ar='الجزائر',cn_iso_2='DZ' WHERE cn_iso_2='DZ';
UPDATE static_countries SET cn_short_ar='الإكوادور',cn_iso_2='EC' WHERE cn_iso_2='EC';
UPDATE static_countries SET cn_short_ar='أستونيا',cn_iso_2='EE' WHERE cn_iso_2='EE';
UPDATE static_countries SET cn_short_ar='مصر',cn_iso_2='EG' WHERE cn_iso_2='EG';
UPDATE static_countries SET cn_short_ar='الصحراء الغربية',cn_iso_2='EH' WHERE cn_iso_2='EH';
UPDATE static_countries SET cn_short_ar='أريتريا',cn_iso_2='ER' WHERE cn_iso_2='ER';
UPDATE static_countries SET cn_short_ar='إسبانيا',cn_iso_2='ES' WHERE cn_iso_2='ES';
UPDATE static_countries SET cn_short_ar='إثيوبيا',cn_iso_2='ET' WHERE cn_iso_2='ET';
UPDATE static_countries SET cn_short_ar='فنلندا',cn_iso_2='FI' WHERE cn_iso_2='FI';
UPDATE static_countries SET cn_short_ar='فيجي',cn_iso_2='FJ' WHERE cn_iso_2='FJ';
UPDATE static_countries SET cn_short_ar='جزر فوكلاند - جزر مالفيناس',cn_iso_2='FK' WHERE cn_iso_2='FK';
UPDATE static_countries SET cn_short_ar='ميكرونيزيا',cn_iso_2='FM' WHERE cn_iso_2='FM';
UPDATE static_countries SET cn_short_ar='جزر فارو',cn_iso_2='FO' WHERE cn_iso_2='FO';
UPDATE static_countries SET cn_short_ar='فرنسا',cn_iso_2='FR' WHERE cn_iso_2='FR';
UPDATE static_countries SET cn_short_ar='الجابون',cn_iso_2='GA' WHERE cn_iso_2='GA';
UPDATE static_countries SET cn_short_ar='المملكة المتحدة',cn_iso_2='GB' WHERE cn_iso_2='GB';
UPDATE static_countries SET cn_short_ar='غرينادا',cn_iso_2='GD' WHERE cn_iso_2='GD';
UPDATE static_countries SET cn_short_ar='جورجيا',cn_iso_2='GE' WHERE cn_iso_2='GE';
UPDATE static_countries SET cn_short_ar='غويانا الفرنسية',cn_iso_2='GF' WHERE cn_iso_2='GF';
UPDATE static_countries SET cn_short_ar='غانا',cn_iso_2='GH' WHERE cn_iso_2='GH';
UPDATE static_countries SET cn_short_ar='جبل طارق',cn_iso_2='GI' WHERE cn_iso_2='GI';
UPDATE static_countries SET cn_short_ar='غرينلاند',cn_iso_2='GL' WHERE cn_iso_2='GL';
UPDATE static_countries SET cn_short_ar='غامبيا',cn_iso_2='GM' WHERE cn_iso_2='GM';
UPDATE static_countries SET cn_short_ar='غينيا',cn_iso_2='GN' WHERE cn_iso_2='GN';
UPDATE static_countries SET cn_short_ar='جوادلوب',cn_iso_2='GP' WHERE cn_iso_2='GP';
UPDATE static_countries SET cn_short_ar='غينيا الإستوائية',cn_iso_2='GQ' WHERE cn_iso_2='GQ';
UPDATE static_countries SET cn_short_ar='اليونان',cn_iso_2='GR' WHERE cn_iso_2='GR';
UPDATE static_countries SET cn_short_ar='جورجيا الجنوبية وجزر ساندويتش الجنوبية',cn_iso_2='GS' WHERE cn_iso_2='GS';
UPDATE static_countries SET cn_short_ar='غواتيمالا',cn_iso_2='GT' WHERE cn_iso_2='GT';
UPDATE static_countries SET cn_short_ar='غوام',cn_iso_2='GU' WHERE cn_iso_2='GU';
UPDATE static_countries SET cn_short_ar='غينيا بيساو',cn_iso_2='GW' WHERE cn_iso_2='GW';
UPDATE static_countries SET cn_short_ar='غيانا',cn_iso_2='GY' WHERE cn_iso_2='GY';
UPDATE static_countries SET cn_short_ar='هونغ كونغ',cn_iso_2='HK' WHERE cn_iso_2='HK';
UPDATE static_countries SET cn_short_ar='هندوراس',cn_iso_2='HN' WHERE cn_iso_2='HN';
UPDATE static_countries SET cn_short_ar='كرواتيا',cn_iso_2='HR' WHERE cn_iso_2='HR';
UPDATE static_countries SET cn_short_ar='هايتي',cn_iso_2='HT' WHERE cn_iso_2='HT';
UPDATE static_countries SET cn_short_ar='هنغاريا',cn_iso_2='HU' WHERE cn_iso_2='HU';
UPDATE static_countries SET cn_short_ar='أندونيسيا',cn_iso_2='ID' WHERE cn_iso_2='ID';
UPDATE static_countries SET cn_short_ar='أيرلندا',cn_iso_2='IE' WHERE cn_iso_2='IE';
UPDATE static_countries SET cn_short_ar='إسرائيل',cn_iso_2='IL' WHERE cn_iso_2='IL';
UPDATE static_countries SET cn_short_ar='الهند',cn_iso_2='IN' WHERE cn_iso_2='IN';
UPDATE static_countries SET cn_short_ar='الإقليم البريطاني في المحيط الهندي',cn_iso_2='IO' WHERE cn_iso_2='IO';
UPDATE static_countries SET cn_short_ar='العراق',cn_iso_2='IQ' WHERE cn_iso_2='IQ';
UPDATE static_countries SET cn_short_ar='إيران',cn_iso_2='IR' WHERE cn_iso_2='IR';
UPDATE static_countries SET cn_short_ar='أيسلندا',cn_iso_2='IS' WHERE cn_iso_2='IS';
UPDATE static_countries SET cn_short_ar='إيطاليا',cn_iso_2='IT' WHERE cn_iso_2='IT';
UPDATE static_countries SET cn_short_ar='جامايكا',cn_iso_2='JM' WHERE cn_iso_2='JM';
UPDATE static_countries SET cn_short_ar='الأردن',cn_iso_2='JO' WHERE cn_iso_2='JO';
UPDATE static_countries SET cn_short_ar='اليابان',cn_iso_2='JP' WHERE cn_iso_2='JP';
UPDATE static_countries SET cn_short_ar='كينيا',cn_iso_2='KE' WHERE cn_iso_2='KE';
UPDATE static_countries SET cn_short_ar='قرغيزستان',cn_iso_2='KG' WHERE cn_iso_2='KG';
UPDATE static_countries SET cn_short_ar='كمبوديا',cn_iso_2='KH' WHERE cn_iso_2='KH';
UPDATE static_countries SET cn_short_ar='كيريباتي',cn_iso_2='KI' WHERE cn_iso_2='KI';
UPDATE static_countries SET cn_short_ar='جزر القمر',cn_iso_2='KM' WHERE cn_iso_2='KM';
UPDATE static_countries SET cn_short_ar='سانت كيتس ونيفيس',cn_iso_2='KN' WHERE cn_iso_2='KN';
UPDATE static_countries SET cn_short_ar='كوريا الشمالية',cn_iso_2='KP' WHERE cn_iso_2='KP';
UPDATE static_countries SET cn_short_ar='كوريا الجنوبية',cn_iso_2='KR' WHERE cn_iso_2='KR';
UPDATE static_countries SET cn_short_ar='الكويت',cn_iso_2='KW' WHERE cn_iso_2='KW';
UPDATE static_countries SET cn_short_ar='جزر الكايمن',cn_iso_2='KY' WHERE cn_iso_2='KY';
UPDATE static_countries SET cn_short_ar='كازاخستان',cn_iso_2='KZ' WHERE cn_iso_2='KZ';
UPDATE static_countries SET cn_short_ar='لاوس',cn_iso_2='LA' WHERE cn_iso_2='LA';
UPDATE static_countries SET cn_short_ar='لبنان',cn_iso_2='LB' WHERE cn_iso_2='LB';
UPDATE static_countries SET cn_short_ar='سانت لوسيا',cn_iso_2='LC' WHERE cn_iso_2='LC';
UPDATE static_countries SET cn_short_ar='ليختنشتاين',cn_iso_2='LI' WHERE cn_iso_2='LI';
UPDATE static_countries SET cn_short_ar='سريلانكا',cn_iso_2='LK' WHERE cn_iso_2='LK';
UPDATE static_countries SET cn_short_ar='ليبيريا',cn_iso_2='LR' WHERE cn_iso_2='LR';
UPDATE static_countries SET cn_short_ar='ليسوتو',cn_iso_2='LS' WHERE cn_iso_2='LS';
UPDATE static_countries SET cn_short_ar='ليتوانيا',cn_iso_2='LT' WHERE cn_iso_2='LT';
UPDATE static_countries SET cn_short_ar='لوكسمبورغ',cn_iso_2='LU' WHERE cn_iso_2='LU';
UPDATE static_countries SET cn_short_ar='لاتفيا',cn_iso_2='LV' WHERE cn_iso_2='LV';
UPDATE static_countries SET cn_short_ar='ليبيا',cn_iso_2='LY' WHERE cn_iso_2='LY';
UPDATE static_countries SET cn_short_ar='المغرب',cn_iso_2='MA' WHERE cn_iso_2='MA';
UPDATE static_countries SET cn_short_ar='موناكو',cn_iso_2='MC' WHERE cn_iso_2='MC';
UPDATE static_countries SET cn_short_ar='مولدافيا',cn_iso_2='MD' WHERE cn_iso_2='MD';
UPDATE static_countries SET cn_short_ar='مدغشقر',cn_iso_2='MG' WHERE cn_iso_2='MG';
UPDATE static_countries SET cn_short_ar='جزر المارشال',cn_iso_2='MH' WHERE cn_iso_2='MH';
UPDATE static_countries SET cn_short_ar='مقدونيا- جمهورية مقدونيا اليوغسلافية السابقة',cn_iso_2='MK' WHERE cn_iso_2='MK';
UPDATE static_countries SET cn_short_ar='مالي',cn_iso_2='ML' WHERE cn_iso_2='ML';
UPDATE static_countries SET cn_short_ar='ميانمار -بورما',cn_iso_2='MM' WHERE cn_iso_2='MM';
UPDATE static_countries SET cn_short_ar='منغوليا',cn_iso_2='MN' WHERE cn_iso_2='MN';
UPDATE static_countries SET cn_short_ar='مكاو',cn_iso_2='MO' WHERE cn_iso_2='MO';
UPDATE static_countries SET cn_short_ar='جزر ماريانا الشمالية',cn_iso_2='MP' WHERE cn_iso_2='MP';
UPDATE static_countries SET cn_short_ar='مارتينيك',cn_iso_2='MQ' WHERE cn_iso_2='MQ';
UPDATE static_countries SET cn_short_ar='موريتانيا',cn_iso_2='MR' WHERE cn_iso_2='MR';
UPDATE static_countries SET cn_short_ar='مونتسرات',cn_iso_2='MS' WHERE cn_iso_2='MS';
UPDATE static_countries SET cn_short_ar='مالطا',cn_iso_2='MT' WHERE cn_iso_2='MT';
UPDATE static_countries SET cn_short_ar='موريشيوس',cn_iso_2='MU' WHERE cn_iso_2='MU';
UPDATE static_countries SET cn_short_ar='جزر المالديف',cn_iso_2='MV' WHERE cn_iso_2='MV';
UPDATE static_countries SET cn_short_ar='ملاوي',cn_iso_2='MW' WHERE cn_iso_2='MW';
UPDATE static_countries SET cn_short_ar='المكسيك',cn_iso_2='MX' WHERE cn_iso_2='MX';
UPDATE static_countries SET cn_short_ar='ماليزيا',cn_iso_2='MY' WHERE cn_iso_2='MY';
UPDATE static_countries SET cn_short_ar='موزمبيق',cn_iso_2='MZ' WHERE cn_iso_2='MZ';
UPDATE static_countries SET cn_short_ar='ناميبيا',cn_iso_2='NA' WHERE cn_iso_2='NA';
UPDATE static_countries SET cn_short_ar='كاليدونيا الجديدة',cn_iso_2='NC' WHERE cn_iso_2='NC';
UPDATE static_countries SET cn_short_ar='النيجر',cn_iso_2='NE' WHERE cn_iso_2='NE';
UPDATE static_countries SET cn_short_ar='جزيرة نورفوك',cn_iso_2='NF' WHERE cn_iso_2='NF';
UPDATE static_countries SET cn_short_ar='نيجيريا',cn_iso_2='NG' WHERE cn_iso_2='NG';
UPDATE static_countries SET cn_short_ar='نيكاراغوا',cn_iso_2='NI' WHERE cn_iso_2='NI';
UPDATE static_countries SET cn_short_ar='هولندا',cn_iso_2='NL' WHERE cn_iso_2='NL';
UPDATE static_countries SET cn_short_ar='النرويج',cn_iso_2='NO' WHERE cn_iso_2='NO';
UPDATE static_countries SET cn_short_ar='نيبال',cn_iso_2='NP' WHERE cn_iso_2='NP';
UPDATE static_countries SET cn_short_ar='ناورو',cn_iso_2='NR' WHERE cn_iso_2='NR';
UPDATE static_countries SET cn_short_ar='نيوي',cn_iso_2='NU' WHERE cn_iso_2='NU';
UPDATE static_countries SET cn_short_ar='نيوزيلاندا',cn_iso_2='NZ' WHERE cn_iso_2='NZ';
UPDATE static_countries SET cn_short_ar='عُمان',cn_iso_2='OM' WHERE cn_iso_2='OM';
UPDATE static_countries SET cn_short_ar='بنما',cn_iso_2='PA' WHERE cn_iso_2='PA';
UPDATE static_countries SET cn_short_ar='بيرو',cn_iso_2='PE' WHERE cn_iso_2='PE';
UPDATE static_countries SET cn_short_ar='بولينيزيا الفرنسية',cn_iso_2='PF' WHERE cn_iso_2='PF';
UPDATE static_countries SET cn_short_ar='بابوا غينيا الجديدة',cn_iso_2='PG' WHERE cn_iso_2='PG';
UPDATE static_countries SET cn_short_ar='الفلبين',cn_iso_2='PH' WHERE cn_iso_2='PH';
UPDATE static_countries SET cn_short_ar='باكستان',cn_iso_2='PK' WHERE cn_iso_2='PK';
UPDATE static_countries SET cn_short_ar='بولندا',cn_iso_2='PL' WHERE cn_iso_2='PL';
UPDATE static_countries SET cn_short_ar='سانت بيير وميكولون',cn_iso_2='PM' WHERE cn_iso_2='PM';
UPDATE static_countries SET cn_short_ar='جزر بيتكيرن',cn_iso_2='PN' WHERE cn_iso_2='PN';
UPDATE static_countries SET cn_short_ar='بورتوريكو',cn_iso_2='PR' WHERE cn_iso_2='PR';
UPDATE static_countries SET cn_short_ar='البرتغال',cn_iso_2='PT' WHERE cn_iso_2='PT';
UPDATE static_countries SET cn_short_ar='بالاو',cn_iso_2='PW' WHERE cn_iso_2='PW';
UPDATE static_countries SET cn_short_ar='باراغواي',cn_iso_2='PY' WHERE cn_iso_2='PY';
UPDATE static_countries SET cn_short_ar='قطر',cn_iso_2='QA' WHERE cn_iso_2='QA';
UPDATE static_countries SET cn_short_ar='روينيون',cn_iso_2='RE' WHERE cn_iso_2='RE';
UPDATE static_countries SET cn_short_ar='رومانيا',cn_iso_2='RO' WHERE cn_iso_2='RO';
UPDATE static_countries SET cn_short_ar='روسيا',cn_iso_2='RU' WHERE cn_iso_2='RU';
UPDATE static_countries SET cn_short_ar='رواندا',cn_iso_2='RW' WHERE cn_iso_2='RW';
UPDATE static_countries SET cn_short_ar='المملكة العربية السعودية',cn_iso_2='SA' WHERE cn_iso_2='SA';
UPDATE static_countries SET cn_short_ar='جزر سليمان',cn_iso_2='SB' WHERE cn_iso_2='SB';
UPDATE static_countries SET cn_short_ar='سيشل',cn_iso_2='SC' WHERE cn_iso_2='SC';
UPDATE static_countries SET cn_short_ar='السودان',cn_iso_2='SD' WHERE cn_iso_2='SD';
UPDATE static_countries SET cn_short_ar='السويد',cn_iso_2='SE' WHERE cn_iso_2='SE';
UPDATE static_countries SET cn_short_ar='سنغافورة',cn_iso_2='SG' WHERE cn_iso_2='SG';
UPDATE static_countries SET cn_short_ar='سانت هيلنا',cn_iso_2='SH' WHERE cn_iso_2='SH';
UPDATE static_countries SET cn_short_ar='سلوفينيا',cn_iso_2='SI' WHERE cn_iso_2='SI';
UPDATE static_countries SET cn_short_ar='سفالبارد وجان مايان',cn_iso_2='SJ' WHERE cn_iso_2='SJ';
UPDATE static_countries SET cn_short_ar='سلوفاكيا',cn_iso_2='SK' WHERE cn_iso_2='SK';
UPDATE static_countries SET cn_short_ar='سيراليون',cn_iso_2='SL' WHERE cn_iso_2='SL';
UPDATE static_countries SET cn_short_ar='سان مارينو',cn_iso_2='SM' WHERE cn_iso_2='SM';
UPDATE static_countries SET cn_short_ar='السنغال',cn_iso_2='SN' WHERE cn_iso_2='SN';
UPDATE static_countries SET cn_short_ar='الصومال',cn_iso_2='SO' WHERE cn_iso_2='SO';
UPDATE static_countries SET cn_short_ar='سورينام',cn_iso_2='SR' WHERE cn_iso_2='SR';
UPDATE static_countries SET cn_short_ar='ساو تومي وبرينسيبي',cn_iso_2='ST' WHERE cn_iso_2='ST';
UPDATE static_countries SET cn_short_ar='السلفادور',cn_iso_2='SV' WHERE cn_iso_2='SV';
UPDATE static_countries SET cn_short_ar='سوريا',cn_iso_2='SY' WHERE cn_iso_2='SY';
UPDATE static_countries SET cn_short_ar='سوازيلاند',cn_iso_2='SZ' WHERE cn_iso_2='SZ';
UPDATE static_countries SET cn_short_ar='جزر الترك وجايكوس',cn_iso_2='TC' WHERE cn_iso_2='TC';
UPDATE static_countries SET cn_short_ar='تشاد',cn_iso_2='TD' WHERE cn_iso_2='TD';
UPDATE static_countries SET cn_short_ar='المقاطعات الجنوبية الفرنسية',cn_iso_2='TF' WHERE cn_iso_2='TF';
UPDATE static_countries SET cn_short_ar='توجو',cn_iso_2='TG' WHERE cn_iso_2='TG';
UPDATE static_countries SET cn_short_ar='تايلاند',cn_iso_2='TH' WHERE cn_iso_2='TH';
UPDATE static_countries SET cn_short_ar='طاجكستان',cn_iso_2='TJ' WHERE cn_iso_2='TJ';
UPDATE static_countries SET cn_short_ar='توكيلو',cn_iso_2='TK' WHERE cn_iso_2='TK';
UPDATE static_countries SET cn_short_ar='تركمانستان',cn_iso_2='TM' WHERE cn_iso_2='TM';
UPDATE static_countries SET cn_short_ar='تونس',cn_iso_2='TN' WHERE cn_iso_2='TN';
UPDATE static_countries SET cn_short_ar='تونغا',cn_iso_2='TO' WHERE cn_iso_2='TO';
UPDATE static_countries SET cn_short_ar='تيمور الشرقية',cn_iso_2='TL' WHERE cn_iso_2='TL';
UPDATE static_countries SET cn_short_ar='تركيا',cn_iso_2='TR' WHERE cn_iso_2='TR';
UPDATE static_countries SET cn_short_ar='ترينيداد وتوباغو',cn_iso_2='TT' WHERE cn_iso_2='TT';
UPDATE static_countries SET cn_short_ar='توفالو',cn_iso_2='TV' WHERE cn_iso_2='TV';
UPDATE static_countries SET cn_short_ar='تايوان',cn_iso_2='TW' WHERE cn_iso_2='TW';
UPDATE static_countries SET cn_short_ar='تانزانيا',cn_iso_2='TZ' WHERE cn_iso_2='TZ';
UPDATE static_countries SET cn_short_ar='أوكرانيا',cn_iso_2='UA' WHERE cn_iso_2='UA';
UPDATE static_countries SET cn_short_ar='أوغندا',cn_iso_2='UG' WHERE cn_iso_2='UG';
UPDATE static_countries SET cn_short_ar='جزر الولايات المتحدة النائية',cn_iso_2='UM' WHERE cn_iso_2='UM';
UPDATE static_countries SET cn_short_ar='الولايات المتحدة',cn_iso_2='US' WHERE cn_iso_2='US';
UPDATE static_countries SET cn_short_ar='أورغواي',cn_iso_2='UY' WHERE cn_iso_2='UY';
UPDATE static_countries SET cn_short_ar='أوزبكستان',cn_iso_2='UZ' WHERE cn_iso_2='UZ';
UPDATE static_countries SET cn_short_ar='الفاتيكان',cn_iso_2='VA' WHERE cn_iso_2='VA';
UPDATE static_countries SET cn_short_ar='سانت فنسنت وغرنادين',cn_iso_2='VC' WHERE cn_iso_2='VC';
UPDATE static_countries SET cn_short_ar='فنزويلا',cn_iso_2='VE' WHERE cn_iso_2='VE';
UPDATE static_countries SET cn_short_ar='جزر فرجين البريطانية',cn_iso_2='VG' WHERE cn_iso_2='VG';
UPDATE static_countries SET cn_short_ar='جزر فرجين الأمريكية',cn_iso_2='VI' WHERE cn_iso_2='VI';
UPDATE static_countries SET cn_short_ar='فيتنام',cn_iso_2='VN' WHERE cn_iso_2='VN';
UPDATE static_countries SET cn_short_ar='فانواتو',cn_iso_2='VU' WHERE cn_iso_2='VU';
UPDATE static_countries SET cn_short_ar='جزر والس وفوتونا',cn_iso_2='WF' WHERE cn_iso_2='WF';
UPDATE static_countries SET cn_short_ar='ساموا',cn_iso_2='WS' WHERE cn_iso_2='WS';
UPDATE static_countries SET cn_short_ar='اليمن',cn_iso_2='YE' WHERE cn_iso_2='YE';
UPDATE static_countries SET cn_short_ar='مايوت',cn_iso_2='YT' WHERE cn_iso_2='YT';
UPDATE static_countries SET cn_short_ar='جنوب أفريقيا',cn_iso_2='ZA' WHERE cn_iso_2='ZA';
UPDATE static_countries SET cn_short_ar='زامبيا',cn_iso_2='ZM' WHERE cn_iso_2='ZM';
UPDATE static_countries SET cn_short_ar='زيمبابوي',cn_iso_2='ZW' WHERE cn_iso_2='ZW';
UPDATE static_countries SET cn_short_ar='فلسطين',cn_iso_2='PS' WHERE cn_iso_2='PS';
UPDATE static_countries SET cn_short_ar='جزر آلاند',cn_iso_2='AX' WHERE cn_iso_2='AX';
UPDATE static_countries SET cn_short_ar='جزيرة هيرد وجزر ماكدونالد',cn_iso_2='HM' WHERE cn_iso_2='HM';
UPDATE static_countries SET cn_short_ar='الجبل الأسود',cn_iso_2='ME' WHERE cn_iso_2='ME';
UPDATE static_countries SET cn_short_ar='صربيا',cn_iso_2='RS' WHERE cn_iso_2='RS';
UPDATE static_countries SET cn_short_ar='جيرسي',cn_iso_2='JE' WHERE cn_iso_2='JE';
UPDATE static_countries SET cn_short_ar='غيرنزي',cn_iso_2='GG' WHERE cn_iso_2='GG';
UPDATE static_countries SET cn_short_ar='جزيرة مان',cn_iso_2='IM' WHERE cn_iso_2='IM';
UPDATE static_countries SET cn_short_ar='سانت مارتن',cn_iso_2='MF' WHERE cn_iso_2='MF';
UPDATE static_countries SET cn_short_ar='سان بارتليمي',cn_iso_2='BL' WHERE cn_iso_2='BL';
UPDATE static_countries SET cn_short_ar='هولندا الكاريبية',cn_iso_2='BQ' WHERE cn_iso_2='BQ';
UPDATE static_countries SET cn_short_ar='كوراساو',cn_iso_2='CW' WHERE cn_iso_2='CW';
UPDATE static_countries SET cn_short_ar='سينت مارتن',cn_iso_2='SX' WHERE cn_iso_2='SX';
UPDATE static_countries SET cn_short_ar='جنوب السودان',cn_iso_2='SS' WHERE cn_iso_2='SS';
UPDATE static_countries SET cn_short_ar='جزيرة أسينشيون',cn_iso_2='AC' WHERE cn_iso_2='AC';
UPDATE static_countries SET cn_short_ar='جزر الأنتيل الهولندية',cn_iso_2='AN' WHERE cn_iso_2='AN';
UPDATE static_countries SET cn_short_ar='جزيرة كليبيرتون',cn_iso_2='CP' WHERE cn_iso_2='CP';
UPDATE static_countries SET cn_short_ar='دييغو غارسيا',cn_iso_2='DG' WHERE cn_iso_2='DG';
UPDATE static_countries SET cn_short_ar='سيوتا وميليلا',cn_iso_2='EA' WHERE cn_iso_2='EA';
UPDATE static_countries SET cn_short_ar='الاتحاد الأوروبي',cn_iso_2='EU' WHERE cn_iso_2='EU';
UPDATE static_countries SET cn_short_ar='جزر الكناري',cn_iso_2='IC' WHERE cn_iso_2='IC';
UPDATE static_countries SET cn_short_ar='أوقيانوسيا النائية',cn_iso_2='QO' WHERE cn_iso_2='QO';
UPDATE static_countries SET cn_short_ar='تريستان دي كونها',cn_iso_2='TA' WHERE cn_iso_2='TA';
UPDATE static_countries SET cn_short_ar='كوسوفو',cn_iso_2='XK' WHERE cn_iso_2='XK';
UPDATE static_countries SET cn_short_ar='منطقة غير معروفة',cn_iso_2='ZZ' WHERE cn_iso_2='ZZ';


## static_languages
UPDATE static_languages SET lg_name_ar='الأبخازية',lg_iso_2='AB' WHERE lg_iso_2='AB';
UPDATE static_languages SET lg_name_ar='الأفارية',lg_iso_2='AA' WHERE lg_iso_2='AA';
UPDATE static_languages SET lg_name_ar='الأفريقية',lg_iso_2='AF' WHERE lg_iso_2='AF';
UPDATE static_languages SET lg_name_ar='الألبانية',lg_iso_2='SQ' WHERE lg_iso_2='SQ';
UPDATE static_languages SET lg_name_ar='الأمهرية',lg_iso_2='AM' WHERE lg_iso_2='AM';
UPDATE static_languages SET lg_name_ar='العربية',lg_iso_2='AR' WHERE lg_iso_2='AR';
UPDATE static_languages SET lg_name_ar='الأرمينية',lg_iso_2='HY' WHERE lg_iso_2='HY';
UPDATE static_languages SET lg_name_ar='الأسامية',lg_iso_2='AS' WHERE lg_iso_2='AS';
UPDATE static_languages SET lg_name_ar='الأيمارا',lg_iso_2='AY' WHERE lg_iso_2='AY';
UPDATE static_languages SET lg_name_ar='الأذرية',lg_iso_2='AZ' WHERE lg_iso_2='AZ';
UPDATE static_languages SET lg_name_ar='الباشكيرية',lg_iso_2='BA' WHERE lg_iso_2='BA';
UPDATE static_languages SET lg_name_ar='لغة الباسك',lg_iso_2='EU' WHERE lg_iso_2='EU';
UPDATE static_languages SET lg_name_ar='البنغالية',lg_iso_2='BN' WHERE lg_iso_2='BN';
UPDATE static_languages SET lg_name_ar='الزونخاية',lg_iso_2='DZ' WHERE lg_iso_2='DZ';
UPDATE static_languages SET lg_name_ar='البيهارية',lg_iso_2='BH' WHERE lg_iso_2='BH';
UPDATE static_languages SET lg_name_ar='البيسلامية',lg_iso_2='BI' WHERE lg_iso_2='BI';
UPDATE static_languages SET lg_name_ar='البريتونية',lg_iso_2='BR' WHERE lg_iso_2='BR';
UPDATE static_languages SET lg_name_ar='البلغارية',lg_iso_2='BG' WHERE lg_iso_2='BG';
UPDATE static_languages SET lg_name_ar='البورمية',lg_iso_2='MY' WHERE lg_iso_2='MY';
UPDATE static_languages SET lg_name_ar='البيلوروسية',lg_iso_2='BE' WHERE lg_iso_2='BE';
UPDATE static_languages SET lg_name_ar='الخميرية',lg_iso_2='KM' WHERE lg_iso_2='KM';
UPDATE static_languages SET lg_name_ar='الكتالانية',lg_iso_2='CA' WHERE lg_iso_2='CA';
UPDATE static_languages SET lg_name_ar='الزهيونج',lg_iso_2='ZA' WHERE lg_iso_2='ZA';
UPDATE static_languages SET lg_name_ar='الصينية',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ar='الكورسيكية',lg_iso_2='CO' WHERE lg_iso_2='CO';
UPDATE static_languages SET lg_name_ar='الكرواتية',lg_iso_2='HR' WHERE lg_iso_2='HR';
UPDATE static_languages SET lg_name_ar='التشيكية',lg_iso_2='CS' WHERE lg_iso_2='CS';
UPDATE static_languages SET lg_name_ar='الدانماركية',lg_iso_2='DA' WHERE lg_iso_2='DA';
UPDATE static_languages SET lg_name_ar='الهولندية',lg_iso_2='NL' WHERE lg_iso_2='NL';
UPDATE static_languages SET lg_name_ar='الإنجليزية',lg_iso_2='EN' WHERE lg_iso_2='EN';
UPDATE static_languages SET lg_name_ar='الإسبرانتو',lg_iso_2='EO' WHERE lg_iso_2='EO';
UPDATE static_languages SET lg_name_ar='الإستونية',lg_iso_2='ET' WHERE lg_iso_2='ET';
UPDATE static_languages SET lg_name_ar='الفارويز',lg_iso_2='FO' WHERE lg_iso_2='FO';
UPDATE static_languages SET lg_name_ar='الفارسية',lg_iso_2='FA' WHERE lg_iso_2='FA';
UPDATE static_languages SET lg_name_ar='الفيجية',lg_iso_2='FJ' WHERE lg_iso_2='FJ';
UPDATE static_languages SET lg_name_ar='الفنلندية',lg_iso_2='FI' WHERE lg_iso_2='FI';
UPDATE static_languages SET lg_name_ar='الفرنسية',lg_iso_2='FR' WHERE lg_iso_2='FR';
UPDATE static_languages SET lg_name_ar='الفريزيان',lg_iso_2='FY' WHERE lg_iso_2='FY';
UPDATE static_languages SET lg_name_ar='الجاليكية',lg_iso_2='GL' WHERE lg_iso_2='GL';
UPDATE static_languages SET lg_name_ar='الغيلية الأسكتلندية',lg_iso_2='GD' WHERE lg_iso_2='GD';
UPDATE static_languages SET lg_name_ar='المنكية',lg_iso_2='GV' WHERE lg_iso_2='GV';
UPDATE static_languages SET lg_name_ar='الجورجية',lg_iso_2='KA' WHERE lg_iso_2='KA';
UPDATE static_languages SET lg_name_ar='الألمانية',lg_iso_2='DE' WHERE lg_iso_2='DE';
UPDATE static_languages SET lg_name_ar='اليونانية',lg_iso_2='EL' WHERE lg_iso_2='EL';
UPDATE static_languages SET lg_name_ar='الكالاليست',lg_iso_2='KL' WHERE lg_iso_2='KL';
UPDATE static_languages SET lg_name_ar='الجواراني',lg_iso_2='GN' WHERE lg_iso_2='GN';
UPDATE static_languages SET lg_name_ar='الغوجاراتية',lg_iso_2='GU' WHERE lg_iso_2='GU';
UPDATE static_languages SET lg_name_ar='الهوسا',lg_iso_2='HA' WHERE lg_iso_2='HA';
UPDATE static_languages SET lg_name_ar='العبرية',lg_iso_2='HE' WHERE lg_iso_2='HE';
UPDATE static_languages SET lg_name_ar='الهندية',lg_iso_2='HI' WHERE lg_iso_2='HI';
UPDATE static_languages SET lg_name_ar='الهنغارية',lg_iso_2='HU' WHERE lg_iso_2='HU';
UPDATE static_languages SET lg_name_ar='الأيسلاندية',lg_iso_2='IS' WHERE lg_iso_2='IS';
UPDATE static_languages SET lg_name_ar='الإندونيسية',lg_iso_2='ID' WHERE lg_iso_2='ID';
UPDATE static_languages SET lg_name_ar='اللّغة الوسيطة',lg_iso_2='IA' WHERE lg_iso_2='IA';
UPDATE static_languages SET lg_name_ar='الإنترلينج',lg_iso_2='IE' WHERE lg_iso_2='IE';
UPDATE static_languages SET lg_name_ar='الإينكتيتت',lg_iso_2='IU' WHERE lg_iso_2='IU';
UPDATE static_languages SET lg_name_ar='الإينبياك',lg_iso_2='IK' WHERE lg_iso_2='IK';
UPDATE static_languages SET lg_name_ar='الأيرلندية',lg_iso_2='GA' WHERE lg_iso_2='GA';
UPDATE static_languages SET lg_name_ar='الإيطالية',lg_iso_2='IT' WHERE lg_iso_2='IT';
UPDATE static_languages SET lg_name_ar='اليابانية',lg_iso_2='JA' WHERE lg_iso_2='JA';
UPDATE static_languages SET lg_name_ar='الكانادا',lg_iso_2='KN' WHERE lg_iso_2='KN';
UPDATE static_languages SET lg_name_ar='الكشميرية',lg_iso_2='KS' WHERE lg_iso_2='KS';
UPDATE static_languages SET lg_name_ar='الكازاخستانية',lg_iso_2='KK' WHERE lg_iso_2='KK';
UPDATE static_languages SET lg_name_ar='الكينيارواندا',lg_iso_2='RW' WHERE lg_iso_2='RW';
UPDATE static_languages SET lg_name_ar='القرغيزية',lg_iso_2='KY' WHERE lg_iso_2='KY';
UPDATE static_languages SET lg_name_ar='الرندي',lg_iso_2='RN' WHERE lg_iso_2='RN';
UPDATE static_languages SET lg_name_ar='الكورية',lg_iso_2='KO' WHERE lg_iso_2='KO';
UPDATE static_languages SET lg_name_ar='الكردية',lg_iso_2='KU' WHERE lg_iso_2='KU';
UPDATE static_languages SET lg_name_ar='اللاوية',lg_iso_2='LO' WHERE lg_iso_2='LO';
UPDATE static_languages SET lg_name_ar='اللاتينية',lg_iso_2='LA' WHERE lg_iso_2='LA';
UPDATE static_languages SET lg_name_ar='اللاتفية',lg_iso_2='LV' WHERE lg_iso_2='LV';
UPDATE static_languages SET lg_name_ar='اللينجالا',lg_iso_2='LN' WHERE lg_iso_2='LN';
UPDATE static_languages SET lg_name_ar='اللتوانية',lg_iso_2='LT' WHERE lg_iso_2='LT';
UPDATE static_languages SET lg_name_ar='المقدونية',lg_iso_2='MK' WHERE lg_iso_2='MK';
UPDATE static_languages SET lg_name_ar='المالاجاشية',lg_iso_2='MG' WHERE lg_iso_2='MG';
UPDATE static_languages SET lg_name_ar='لغة الملايو',lg_iso_2='MS' WHERE lg_iso_2='MS';
UPDATE static_languages SET lg_name_ar='الماليالام',lg_iso_2='ML' WHERE lg_iso_2='ML';
UPDATE static_languages SET lg_name_ar='المالطية',lg_iso_2='MT' WHERE lg_iso_2='MT';
UPDATE static_languages SET lg_name_ar='الماورية',lg_iso_2='MI' WHERE lg_iso_2='MI';
UPDATE static_languages SET lg_name_ar='الماراثي',lg_iso_2='MR' WHERE lg_iso_2='MR';
UPDATE static_languages SET lg_name_ar='المولدوفية',lg_iso_2='MO' WHERE lg_iso_2='MO';
UPDATE static_languages SET lg_name_ar='المنغولية',lg_iso_2='MN' WHERE lg_iso_2='MN';
UPDATE static_languages SET lg_name_ar='النورو',lg_iso_2='NA' WHERE lg_iso_2='NA';
UPDATE static_languages SET lg_name_ar='النيبالية',lg_iso_2='NE' WHERE lg_iso_2='NE';
UPDATE static_languages SET lg_name_ar='النرويجية',lg_iso_2='NO' WHERE lg_iso_2='NO';
UPDATE static_languages SET lg_name_ar='الأوكيتانية',lg_iso_2='OC' WHERE lg_iso_2='OC';
UPDATE static_languages SET lg_name_ar='الأورييا',lg_iso_2='OR' WHERE lg_iso_2='OR';
UPDATE static_languages SET lg_name_ar='الأورومو',lg_iso_2='OM' WHERE lg_iso_2='OM';
UPDATE static_languages SET lg_name_ar='بشتو',lg_iso_2='PS' WHERE lg_iso_2='PS';
UPDATE static_languages SET lg_name_ar='البولندية',lg_iso_2='PL' WHERE lg_iso_2='PL';
UPDATE static_languages SET lg_name_ar='البرتغالية',lg_iso_2='PT' WHERE lg_iso_2='PT';
UPDATE static_languages SET lg_name_ar='البنجابية',lg_iso_2='PA' WHERE lg_iso_2='PA';
UPDATE static_languages SET lg_name_ar='الكويتشوا',lg_iso_2='QU' WHERE lg_iso_2='QU';
UPDATE static_languages SET lg_name_ar='الرومانشية',lg_iso_2='RM' WHERE lg_iso_2='RM';
UPDATE static_languages SET lg_name_ar='الرومانية',lg_iso_2='RO' WHERE lg_iso_2='RO';
UPDATE static_languages SET lg_name_ar='الروسية',lg_iso_2='RU' WHERE lg_iso_2='RU';
UPDATE static_languages SET lg_name_ar='الساموائية',lg_iso_2='SM' WHERE lg_iso_2='SM';
UPDATE static_languages SET lg_name_ar='السانجو',lg_iso_2='SG' WHERE lg_iso_2='SG';
UPDATE static_languages SET lg_name_ar='السنسكريتية',lg_iso_2='SA' WHERE lg_iso_2='SA';
UPDATE static_languages SET lg_name_ar='الصربية',lg_iso_2='SR' WHERE lg_iso_2='SR';
UPDATE static_languages SET lg_name_ar='السوتو الجنوبية',lg_iso_2='ST' WHERE lg_iso_2='ST';
UPDATE static_languages SET lg_name_ar='التسوانية',lg_iso_2='TN' WHERE lg_iso_2='TN';
UPDATE static_languages SET lg_name_ar='الشونا',lg_iso_2='SN' WHERE lg_iso_2='SN';
UPDATE static_languages SET lg_name_ar='السندية',lg_iso_2='SD' WHERE lg_iso_2='SD';
UPDATE static_languages SET lg_name_ar='السنهالية',lg_iso_2='SI' WHERE lg_iso_2='SI';
UPDATE static_languages SET lg_name_ar='السواتي',lg_iso_2='SS' WHERE lg_iso_2='SS';
UPDATE static_languages SET lg_name_ar='السلوفاكية',lg_iso_2='SK' WHERE lg_iso_2='SK';
UPDATE static_languages SET lg_name_ar='السلوفانية',lg_iso_2='SL' WHERE lg_iso_2='SL';
UPDATE static_languages SET lg_name_ar='الصومالية',lg_iso_2='SO' WHERE lg_iso_2='SO';
UPDATE static_languages SET lg_name_ar='الإسبانية',lg_iso_2='ES' WHERE lg_iso_2='ES';
UPDATE static_languages SET lg_name_ar='السوندانية',lg_iso_2='SU' WHERE lg_iso_2='SU';
UPDATE static_languages SET lg_name_ar='السواحلية',lg_iso_2='SW' WHERE lg_iso_2='SW';
UPDATE static_languages SET lg_name_ar='السويدية',lg_iso_2='SV' WHERE lg_iso_2='SV';
UPDATE static_languages SET lg_name_ar='التاغالوغية',lg_iso_2='TL' WHERE lg_iso_2='TL';
UPDATE static_languages SET lg_name_ar='الطاجيكية',lg_iso_2='TG' WHERE lg_iso_2='TG';
UPDATE static_languages SET lg_name_ar='التاميلية',lg_iso_2='TA' WHERE lg_iso_2='TA';
UPDATE static_languages SET lg_name_ar='التتارية',lg_iso_2='TT' WHERE lg_iso_2='TT';
UPDATE static_languages SET lg_name_ar='التيلجو',lg_iso_2='TE' WHERE lg_iso_2='TE';
UPDATE static_languages SET lg_name_ar='التايلاندية',lg_iso_2='TH' WHERE lg_iso_2='TH';
UPDATE static_languages SET lg_name_ar='التبتية',lg_iso_2='BO' WHERE lg_iso_2='BO';
UPDATE static_languages SET lg_name_ar='التيجرينيا',lg_iso_2='TI' WHERE lg_iso_2='TI';
UPDATE static_languages SET lg_name_ar='التونغية',lg_iso_2='TO' WHERE lg_iso_2='TO';
UPDATE static_languages SET lg_name_ar='السونجا',lg_iso_2='TS' WHERE lg_iso_2='TS';
UPDATE static_languages SET lg_name_ar='التركية',lg_iso_2='TR' WHERE lg_iso_2='TR';
UPDATE static_languages SET lg_name_ar='التركمانية',lg_iso_2='TK' WHERE lg_iso_2='TK';
UPDATE static_languages SET lg_name_ar='التوي',lg_iso_2='TW' WHERE lg_iso_2='TW';
UPDATE static_languages SET lg_name_ar='الأيغورية',lg_iso_2='UG' WHERE lg_iso_2='UG';
UPDATE static_languages SET lg_name_ar='الأوكرانية',lg_iso_2='UK' WHERE lg_iso_2='UK';
UPDATE static_languages SET lg_name_ar='الأردية',lg_iso_2='UR' WHERE lg_iso_2='UR';
UPDATE static_languages SET lg_name_ar='الأوزباكية',lg_iso_2='UZ' WHERE lg_iso_2='UZ';
UPDATE static_languages SET lg_name_ar='الفيتنامية',lg_iso_2='VI' WHERE lg_iso_2='VI';
UPDATE static_languages SET lg_name_ar='',lg_iso_2='VO' WHERE lg_iso_2='VO';
UPDATE static_languages SET lg_name_ar='الولزية',lg_iso_2='CY' WHERE lg_iso_2='CY';
UPDATE static_languages SET lg_name_ar='الولوف',lg_iso_2='WO' WHERE lg_iso_2='WO';
UPDATE static_languages SET lg_name_ar='الخوسا',lg_iso_2='XH' WHERE lg_iso_2='XH';
UPDATE static_languages SET lg_name_ar='اليديشية',lg_iso_2='YI' WHERE lg_iso_2='YI';
UPDATE static_languages SET lg_name_ar='اليوروبية',lg_iso_2='YO' WHERE lg_iso_2='YO';
UPDATE static_languages SET lg_name_ar='الزولو',lg_iso_2='ZU' WHERE lg_iso_2='ZU';
UPDATE static_languages SET lg_name_ar='البوسنية',lg_iso_2='BS' WHERE lg_iso_2='BS';
UPDATE static_languages SET lg_name_ar='الأفستية',lg_iso_2='AE' WHERE lg_iso_2='AE';
UPDATE static_languages SET lg_name_ar='الأكانية',lg_iso_2='AK' WHERE lg_iso_2='AK';
UPDATE static_languages SET lg_name_ar='الأراجونية',lg_iso_2='AN' WHERE lg_iso_2='AN';
UPDATE static_languages SET lg_name_ar='الأفاريكية',lg_iso_2='AV' WHERE lg_iso_2='AV';
UPDATE static_languages SET lg_name_ar='البامبارا',lg_iso_2='BM' WHERE lg_iso_2='BM';
UPDATE static_languages SET lg_name_ar='الشيشانية',lg_iso_2='CE' WHERE lg_iso_2='CE';
UPDATE static_languages SET lg_name_ar='التشامورو',lg_iso_2='CH' WHERE lg_iso_2='CH';
UPDATE static_languages SET lg_name_ar='الكرى',lg_iso_2='CR' WHERE lg_iso_2='CR';
UPDATE static_languages SET lg_name_ar='سلافية كنسية',lg_iso_2='CU' WHERE lg_iso_2='CU';
UPDATE static_languages SET lg_name_ar='التشفاش',lg_iso_2='CV' WHERE lg_iso_2='CV';
UPDATE static_languages SET lg_name_ar='المالديفية',lg_iso_2='DV' WHERE lg_iso_2='DV';
UPDATE static_languages SET lg_name_ar='الإيوي',lg_iso_2='EE' WHERE lg_iso_2='EE';
UPDATE static_languages SET lg_name_ar='الفلة',lg_iso_2='FF' WHERE lg_iso_2='FF';
UPDATE static_languages SET lg_name_ar='الهيري موتو',lg_iso_2='HO' WHERE lg_iso_2='HO';
UPDATE static_languages SET lg_name_ar='الهايتية',lg_iso_2='HT' WHERE lg_iso_2='HT';
UPDATE static_languages SET lg_name_ar='الهيريرو',lg_iso_2='HZ' WHERE lg_iso_2='HZ';
UPDATE static_languages SET lg_name_ar='الإيجبو',lg_iso_2='IG' WHERE lg_iso_2='IG';
UPDATE static_languages SET lg_name_ar='السيتشيون يي',lg_iso_2='II' WHERE lg_iso_2='II';
UPDATE static_languages SET lg_name_ar='الإيدو',lg_iso_2='IO' WHERE lg_iso_2='IO';
UPDATE static_languages SET lg_name_ar='الجاوية',lg_iso_2='JV' WHERE lg_iso_2='JV';
UPDATE static_languages SET lg_name_ar='الكونغو',lg_iso_2='KG' WHERE lg_iso_2='KG';
UPDATE static_languages SET lg_name_ar='الكيكيو',lg_iso_2='KI' WHERE lg_iso_2='KI';
UPDATE static_languages SET lg_name_ar='الكيونياما',lg_iso_2='KJ' WHERE lg_iso_2='KJ';
UPDATE static_languages SET lg_name_ar='الكانيوري',lg_iso_2='KR' WHERE lg_iso_2='KR';
UPDATE static_languages SET lg_name_ar='الكومي',lg_iso_2='KV' WHERE lg_iso_2='KV';
UPDATE static_languages SET lg_name_ar='الكورنية',lg_iso_2='KW' WHERE lg_iso_2='KW';
UPDATE static_languages SET lg_name_ar='اللوكسمبرجية',lg_iso_2='LB' WHERE lg_iso_2='LB';
UPDATE static_languages SET lg_name_ar='الجاندا',lg_iso_2='LG' WHERE lg_iso_2='LG';
UPDATE static_languages SET lg_name_ar='الليمبرجيشية',lg_iso_2='LI' WHERE lg_iso_2='LI';
UPDATE static_languages SET lg_name_ar='اللبا-كاتانجا',lg_iso_2='LU' WHERE lg_iso_2='LU';
UPDATE static_languages SET lg_name_ar='المارشالية',lg_iso_2='MH' WHERE lg_iso_2='MH';
UPDATE static_languages SET lg_name_ar='البوكمالية النرويجية',lg_iso_2='NB' WHERE lg_iso_2='NB';
UPDATE static_languages SET lg_name_ar='النديبيل الشمالي',lg_iso_2='ND' WHERE lg_iso_2='ND';
UPDATE static_languages SET lg_name_ar='الندونجا',lg_iso_2='NG' WHERE lg_iso_2='NG';
UPDATE static_languages SET lg_name_ar='النينورسك النرويجي',lg_iso_2='NN' WHERE lg_iso_2='NN';
UPDATE static_languages SET lg_name_ar='النديبيل الجنوبي',lg_iso_2='NR' WHERE lg_iso_2='NR';
UPDATE static_languages SET lg_name_ar='النافاجو',lg_iso_2='NV' WHERE lg_iso_2='NV';
UPDATE static_languages SET lg_name_ar='النيانجا',lg_iso_2='NY' WHERE lg_iso_2='NY';
UPDATE static_languages SET lg_name_ar='الأوجيبوا',lg_iso_2='OJ' WHERE lg_iso_2='OJ';
UPDATE static_languages SET lg_name_ar='الأوسيتيك',lg_iso_2='OS' WHERE lg_iso_2='OS';
UPDATE static_languages SET lg_name_ar='البالية',lg_iso_2='PI' WHERE lg_iso_2='PI';
UPDATE static_languages SET lg_name_ar='السردينية',lg_iso_2='SC' WHERE lg_iso_2='SC';
UPDATE static_languages SET lg_name_ar='السامي الشمالي',lg_iso_2='SE' WHERE lg_iso_2='SE';
UPDATE static_languages SET lg_name_ar='التاهيتية',lg_iso_2='TY' WHERE lg_iso_2='TY';
UPDATE static_languages SET lg_name_ar='الفيندا',lg_iso_2='VE' WHERE lg_iso_2='VE';
UPDATE static_languages SET lg_name_ar='الولونية',lg_iso_2='WA' WHERE lg_iso_2='WA';
UPDATE static_languages SET lg_name_ar='البرتغالية',lg_iso_2='PT' WHERE lg_iso_2='PT';
UPDATE static_languages SET lg_name_ar='الصينية',lg_iso_2='ZH' WHERE lg_iso_2='ZH';
UPDATE static_languages SET lg_name_ar='الفرنسية',lg_iso_2='FR' WHERE lg_iso_2='FR';
UPDATE static_languages SET lg_name_ar='التاغالوغية',lg_iso_2='TL' WHERE lg_iso_2='TL';
UPDATE static_languages SET lg_name_ar='',lg_iso_2='SH' WHERE lg_iso_2='SH';


